language: erlang
install: true
# env:
#   - REBAR_BUILD=github
#   - REBAR_BUILD=gitlab
#   - REBAR_BUILD=hexpm
script:
  - make build-github
  - make check
  #- make check-hexpm # XXX disabled due to Hex.pm failing on R15
otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3
  - 18.3
  - 17.5
# matrix:
#   # disabled due to Hex.pm failing on R15
#   exclude:
#   - otp_release: R15B03
#     env: REBAR_BUILD=hexpm
