name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
  schedule:
  - cron: "8 4 12 * *"

jobs:

  core-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: ['24.3', '25.3', '26.0']

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    #- name: Xref Checks
    #  run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tunit
    - name: Run Integration Tests
      run: rebar3 as test lfe ltest -tintegration
    #- name: Test Coverage
    #  run: rebar3 as test do proper -c, cover -v --min_coverage=0

  old-builds:
    name: Old Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        # XXX Once the fix for Erl 26.0 is in place for rebar3, we can re-enable
        # 20.3 in CI/CD. More info here:
        # * https://github.com/lfe/rebar3/issues/82
        # * https://github.com/erlang/rebar3/issues/2817
        #otp_version: ['20.3', '21.3', '22.3', '23.3']
        otp_version: ['21.3', '22.3', '23.3']

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    #- name: Xref Checks
    #  run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tunit
    - name: Run Integration Tests
      run: rebar3 as test lfe ltest -tintegration
    #- name: Test Coverage
    #  run: rebar3 as test do proper -c, cover -v --min_coverage=0
