name: ci/cd

on:
  push:
    branches: [ master, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ master, 'release/**', 'task/**', 'feature/**', 'epic/**']
  schedule:
  - cron: "8 4 12 * *"
  
jobs:

  build:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23, 24]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: DIAGNOSTIC=1 rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
#    - name: Dialyzer
#      run: rebar3 dialyzer
    - name: Compile Test Profile
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tunit
    - name: Run Integration Tests
      run: rebar3 as test lfe ltest -tintegration
    - name: Test Coverage
      run: rebar3 as test do proper -c, cover -v --min_coverage=0
